### ISSUE TITLE
Relax `oj` dependency

### ISSUE THREAD

**Issue by bibendi** [panko-serializer/panko_serializer#107]
Please relax `oj` dependency to `~> 3.11`.

**Comment by yosiat** [comment]
@bibendi have you seen the latest version ?
https://github.com/panko-serializer/panko_serializer/blob/master/panko_serializer.gemspec#L33

If this is about the latest version, what's the problem you are experiencing there?

**Comment by bibendi** [comment]
LGTM!
Thank you for the fix.

**Comment by yosiat** [comment]
Happy it solved your issue :)

Closing the issue, if you have any new issues, feel free to open new one.
