### ISSUE TITLE
Filter on array serializer?

### ISSUE THREAD

**Issue by mahdiar-naufal-shyftplan** [panko-serializer/panko_serializer#140]
Right now we are able to filter on singular serializer
```
class UserSerializer < Panko::Serializer
  attributes :id, :name, :email
end

# this line will return { 'name': '..' }
UserSerializer.new(only: [:name]).serialize(User.first)

# this line will return { 'id': '..', 'email': ... }
UserSerializer.new(except: [:name]).serialize(User.first)
```

But do you think we can apply that filter if we are using ArraySerializer?
```
Panko::ArraySerializer.new(users, each_serializer: UserSerializer)
```

**Comment by yosiat** [comment]
@mahdiar-naufal-shyftplan please see the docs regarding `Nested Filters` - https://panko.dev/docs/associations#nested-filters

**Comment by mahdiar-naufal-shyftplan** [comment]
I see, that's doable for same filter on each array element. Thank you @yosiat!

Do they also able to handle the different filter on each element?

For an example in array index
0 i want to keep only the `id` keys, but on array index 1 I want to keep only the `id` and `name` keys

**Comment by yosiat** [comment]
> Do they also able to handle the different filter on each element?

It's not possible as of today and it's something a bit complex to implement, to support filtering based json-paths. It's not something I plan to add support for, but maybe in the future I'll come up with extension point that will allow choose custom filtering logic.

**Comment by mahdiar-naufal-shyftplan** [comment]
Thanks!
